### PR TITLE
chore: update jquery

### PR DESCRIPTION
**Pull request by RobertFridolin**
As long as it's there, it should be the updated version.

### CODE REVIEW

**Comment by ZoeBijl** [comment]
Good idea! In future could you create an issue for things first? That way we can more easily assign it to projects and milestones :)

Have you done much testing to verify the new version doesn’t break anything?

**Comment by RobertFridolin** [comment]
Sorry, sure i can do. As far as i know Priller changed on his version to newest one too and there have been no problems as far as i know. https://forums.airlinesim.aero/t/introducing-airlinesim-enhancement-suite-beta/21684/76

I also checked again yesterday noticed no issues.

**Comment by ZoeBijl** [comment]
Could you put jquery in a `vendor` folder? After that this looks ready to go!

I’d like to do some folder restructuring soon and this would make a good start to that project.

**Comment by RobertFridolin** [comment]
/js/vendor/jquery-3.7.1.slim.min.js you mean?

**Comment by RobertFridolin** [comment]
seems like the directory was somehow wrong anyway because I had it twice in my project :grimacing:

**Comment by ZoeBijl** [comment]
I rather meant `/vendor/jquery.js` but I’ll move it after merging :)

**Pull request merged**
